---

- name: Configure vPC on leaf switches.
  hosts: vpc101
  connection: local
  gather_facts: no

  tasks:

  - name: Check feature enablement for required features.
    checkFeatures:
      device={{ inventory_hostname }}
      username=admin
      password=cisco123
    register: features

  - debug: msg="{{ features.status }}"
