---

- name: Configure vPC on leaf switches.
  hosts: vpc101
  connection: local
  gather_facts: no

  tasks:

  - name: Check feature enablement for required features.
    checkFeatures:
      device={{ inventory_hostname }}
      username=admin
      password=cisco123
    register: features


  - name: Build vPC domain on peer switches.
    nxapi_vpc:
      device={{ inventory_hostname }}
      username=admin
      password=cisco123
      fact=vpc_id
      vpcID=20
    register: vpcdomain

  - debug: msg="{{ features.status }}"

  - debug: msg="{{ vpcdomain.status }}"
