---

- name: gather facts from nexus 9000 switches
  hosts: switches
  connection: local
  gather_facts: no

  tasks:

  - name: get facts from device
    nxapi_vpc: device={{ inventory_hostname }}
     username=admin
     password=cisco123
     fact=vpc_id
     vpcID=20
    register: my_facts

  - debug: msg="{{ my_facts.status }}"
